name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  protect-main:
    name: Protect Main Branch
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.event.pusher.name != 'web-flow' && github.event.pusher.name != 'github-actions[bot]'
    steps:
      - name: Fail run
        run: |
          echo "Direct pushes to main are disabled. Open a pull request instead."
          exit 1

  quality-gate:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix['node-version'] }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run typecheck

      - name: Unit tests
        run: npm test
